<<<<<<< HEAD
#Tue Feb 11 10:29:16 ICT 2025
execution.default.selectingCapturedObjectSelectorMethod="XPATH"
=======
#Tue Feb 11 10:29:16 ICT 2025
execution.default.selectingCapturedObjectSelectorMethod="XPATH"
>>>>>>> branch 'master' of https://github.com/vikim97/customize-chrome-download-path.git
