<<<<<<< HEAD
kobitonDeviceId=
remoteWebDriverType=Selenium
adoPlanID=
testcloudMobileId=
deviceId=
testOpsProjectId=
testcloudMobileDeviceId=
testcloudAppId=
testOpsBuildId=
testOps.serverUrl=
testcloudEnvironmentID=
adoTestRunName=
testcloudTunnel=
kobitonUserName=
adoPlanId=
testcloudMobileID=
kobitonToken=
testOps.enabled=
testcloudMobileDeviceID=
testOpsReleaseId=
qTestDestId=
appiumDirectory=
qTestDestType=
testcloudEnvironmentId=
remoteWebDriverUrl=
overrideTestcloudAppId=
=======
kobitonDeviceId=
remoteWebDriverType=Selenium
adoPlanID=
testcloudMobileId=
deviceId=
testOpsProjectId=
testcloudMobileDeviceId=
testcloudAppId=
testOpsBuildId=
testOps.serverUrl=
testcloudEnvironmentID=
adoTestRunName=
testcloudTunnel=
kobitonUserName=
adoPlanId=
testcloudMobileID=
kobitonToken=
testOps.enabled=
testcloudMobileDeviceID=
testOpsReleaseId=
qTestDestId=
appiumDirectory=
qTestDestType=
testcloudEnvironmentId=
remoteWebDriverUrl=
overrideTestcloudAppId=
>>>>>>> branch 'master' of https://github.com/vikim97/customize-chrome-download-path.git
